edition = "2021"
format_code_in_doc_comments = true
format_strings = true
max_width = 100
merge_imports = true
reorder_impl_items = true
reorder_imports = true
tab_spaces = 4
use_field_init_shorthand = true
wrap_comments = true
